ТЗ 9 Первое ревью
MayFoxes/java-filmorate pull request #6
Opened 2024-02-14 11:58 UTC by MayFoxes

2024-02-15 06:46 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-02-15 06:46 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void idGenerated() {
Может лучше сразу возвращать идентификатор после того, как обновили это поле

2024-02-15 06:46 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
`else` не нужен, так как делаешь `return` в ветке условного оператора

2024-02-15 06:46 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @RequestMapping("/films")
А зачем здесь `RequestMapping`? Почему также как ниже не использовать параметр `value`

2024-02-15 06:46 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Замечания аналогичные `FilmController`

2024-02-15 06:46 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            users.put(user.getId(), user);
потеряна проверка, которая есть при создании пользователя на заполнение пустого имени

2024-02-15 06:46 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public String toString() {
`@Override`

2024-02-15 06:46 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public String toString() {
`@Override`

2024-02-15 08:21 UTC, MayFoxes commented
Исправил замечания

2024-02-16 06:24 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-02-16 13:03 UTC, merged