feat: HW 10 - first review
MayFoxes/java-filmorate pull request #7
Opened 2024-02-26 12:36 UTC by MayFoxes

Переработана архитектура. Созданы интерфейсы FilmStorage и UserStorage.
Созданы классы InMemoryFilmStorage и InMemoryUserStorage, имплементирующие новые интерфейсы.
По той же логике созданы UserService и FilmService. Внедрены зависимости.
Настроена обработка ошибок.
Добавлены функции добавления друзей и лайков фильмов. 
Изменены тесты.

2024-02-27 06:53 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пару замечаний, которые необходимо исправить!

Желаю удачи!

2024-02-27 06:53 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(defaultValue = "10", required = false) @PositiveOrZero Integer count
Если указываем параметр `defaultValue`, то `required = false` встает автоматически:
https://www.baeldung.com/spring-request-param#a-default-value-for-the-request-parameter

2024-02-27 06:53 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> likes = new HashSet<>();
Для этого поля стоит переопределить `getter`, чтобы возвращать не саму коллекцию, а ее копию, иначе нарушается инкапсуляция объекта. 

Для модификации этого поля стоит сделать отдельные методы

2024-02-27 06:53 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> friends = new HashSet<>();
Аналогично тому, что в `Film` написал

2024-02-27 09:17 UTC, MayFoxes commented
Исправил замечания

2024-02-28 06:32 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-03-10 09:51 UTC, merged