HW-11: add database
MayFoxes/java-filmorate pull request #9
Opened 2024-03-28 14:30 UTC by MayFoxes

Для UserStorage и FilmStorage создана новая имплементация — UserDbStorage и FilmDbStorage, эти классы — DAO объекты доступа к данным.
Также созданы MpaStorage и GenreStorage с соответствующей имплементацией.
В DAO реализованы соответствующие мапперы и методы, позволяющие сохранять пользователей и фильмы в базу данных и получать их из неё.

2024-03-29 13:36 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-03-29 13:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +);
Таблице не хватает первичного ключа

2024-03-29 13:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +);
Таблице не хватает первичного ключа

2024-03-29 13:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +);
Таблице не хватает первичного ключа

2024-03-29 13:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +    EMAIL    VARCHAR(50) NOT NULL,
`email` может быть куда длиннее:

https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

2024-03-29 13:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Вот от этой команды необходимо избавиться.
Никто не захочет пользоваться приложением, в котором данные пользователя удаляются после каждого релиза

2024-03-29 13:36 UTC, LexLippi commented on src/main/resources/data.sql
> +VALUES('Комедия'),('Драма'),('Мультфильм'),('Триллер'),('Документальный'),('Боевик');
Лучше использовать оператор `MERGE`

2024-03-29 13:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<User> getCommonFriends(@PathVariable("id") Integer id, @PathVariable("otherId") Integer otherId) {
Названия не нужны, если они совпадают с названием переменных

2024-03-29 13:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@EqualsAndHashCode
Это аннотация уже содержится внутри `@Data`

2024-03-29 13:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +@EqualsAndHashCode
Уже содержится внутри `@Data`

2024-03-29 13:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/FilmDbStorage.java
> +    private final GenreDbStorage genreDbStorage;
Не должны напрямую обращаться к реализации хранилища, только к интерфейсу

2024-03-29 23:03 UTC, MayFoxes commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/dao/FilmDbStorage.java
> +            String sqlInsert = "MERGE INTO FILM_GENRE (FILM_ID, GENRE_ID) VALUES (?, ?) ";
Подправил замечания. Также заменил sql запрос в обновлении жанра для фильма.

2024-04-01 03:14 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@RequiredArgsConstructor
у тебя местами @RequiredArgsConstructor, а местами @AllArgsConstructor. В проекте должно быть все одннобразно. выбери пожалуйста что то одно

2024-04-01 03:14 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
>  @RestControllerAdvice
пожалуйста залогируй здесь ошибки на уровень log.error  или log.debug

2024-04-01 06:49 UTC, MayFoxes commented
Подправил аннотации.
Добавил логирование ошибок на уровень log.error.

2024-04-01 19:13 UTC, merged